### ISSUE TITLE
idea: Download 'exiftool' to 'tools::R_user_dir("exiftoolr")'

### ISSUE THREAD

**Issue by trevorld** [JoshOBrien/exiftoolr#10]
* `tools::R_user_dir("exiftoolr")` should generally be more writable by users than `system.file(package = "exiftoolr")`.

  + In particular the case where `exiftoolr` is installed by an admin in the shared library of a multi-user server (and hence is owned by "root").  I already have a system install of `exiftool` so this isn't a problem but my attempt of using `install_exiftool()` to see what happens failed for this reason.

* Not sure if it would be better to use `R_user_dir("exiftoolr", "data")` (default) versus `R_user_dir("exiftoolr", "config")` versus `R_user_dir("exiftoolr", "cache")` but it probably doesn't matter too much which one is chosen.

* `R_user_dir()` was introduced in R 4.0.0 so you'd need to bump your R version requirement or use the `{backports}` version

**Comment by JoshOBrien** [comment]
@trevorld These are great ideas -- thanks! --  and if you would like to prep a PR implementing them, I'd happily look it over and then merge it. If not, I'll likely get to this eventually, but not for at least a few weeks.

FWIW, using `R_user_dir("exiftoolr", "data")` makes best sense to me. Also, I'd strongly prefer to not add an R version requirement, so would want to use the version of `R_user_dir()` made available by **backports**.
