### ISSUE TITLE
why is the app detected as Threat by Bitdefender . 

### ISSUE THREAD

**Issue by DrPhysiker** [JoshOBrien/exiftoolr#17]
![image](https://github.com/JoshOBrien/exiftoolr/assets/30960624/b7afab98-3191-4d19-ba2d-ecc32e45045d)

**Comment by JoshOBrien** [comment]
@DrPhysiker It's not detecting my R package. It looks like it's detecting ExifTool ([homepage here](https://exiftool.org/)), the app for which my package is just a wrapper. So this is an issue for either ExifTool or Bitdefender.
