### ISSUE TITLE
exif_call not recognizing custom config file or -config tag

### ISSUE THREAD

**Issue by burnsal** [JoshOBrien/exiftoolr#19]
Hello, 

I am using your package as a dependency in my own R package to extract image metadata, and I am trying to develop functionality to write metadata to image files as well. I have developed a custom config file using the [exiftool config template](https://exiftool.org/config.html) and troubleshooted my custom tags with help from the [exiftool forum](https://exiftool.org/forum/index.php?topic=3885.0)

 However, whenever I try to use `exif_call` to write new tags, I receive the following error: `"Warning: Tag 'config' is not defined"` All tags created in my config file are subsequently undefined. I have tried saving the config file with a .config extension and a .cfg extension with the same result. I have been able to successfully use this approach with the exiftool installation from your package on the command line, and can see the new tags when I call the image in the `exif_read` function. This makes me think the issue has something to do with the `exif_call` function not recognizing the `-config` tag.

Please let me know if I can provide any further detail to address this issue. Thank you for any assistance!

**Comment by JoshOBrien** [comment]
Hi there,

Would you mind attaching a sample photo, along with both:

- a command-line call that does work for you
- the equivalent but failing call to `exif_call()`

Having a reproducible example showing me what you're trying and how it's failing will make this tons easier for me to look into.

Thanks!

- Josh

**Comment by burnsal** [comment]
@JoshOBrien Yes of course.

Here is the successful command line prompt. I made sure to use the version of exiftool that exiftoolr uses:
![commandline](https://github.com/JoshOBrien/exiftoolr/assets/54477812/1a993980-80a8-4bab-835b-97f2658954cd)

And here is the corresponding code and output from RStudio, including the full error message:
![RStudio](https://github.com/JoshOBrien/exiftoolr/assets/54477812/1baf5e0f-08cd-4240-9856-92ef6100a00f)

I'm also attaching the config file for your testing, just in case the formatting there is part of the issue.
[cameratrapdetector_metadata.zip](https://github.com/JoshOBrien/exiftoolr/files/12847343/cameratrapdetector_metadata.zip)

Thank you again!

**Comment by JoshOBrien** [comment]
Thanks. Would you mind also attaching the file "American_Badger_CA.jpg"? Or, if you can't share that, would you let me know if the same example works with one of the image files that ships with my package, say the one at the path given by:

```r
system.file("images/LaSals.jpg", package = "exiftoolr")
```

Also, if you don't mind, would you copy the code in your screenshots into a code block ([as here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)) so that I can copy and paste it?

Thanks!

- Josh

**Comment by burnsal** [comment]
Surely. I've redacted pathways.

Command line code: 
"""
cd \path\to\exiftool
exiftool -config "C:\path\to\cameratrapdetector_metadata.cfg" -XMP-ctd:CTD_SpV2PredictedClass="AmericanBadger" "C:\path\to\image\American_Badger_CA.jpg" 
"""

RStudio code:
"""
config_file <- "C:/path/to/cameratrapdetector_metadata.cfg"
test_img <- "C:/path/to/image/American_Badger_CA.jpg"
exif_call_test <- c(paste0("-config=", config_file),
                    paste0(" -XMP-ctd:CTD_SpV2_PredictedClass=", "American_Badger"))
exiftoolr::exif_call(args = exif_call_test, path = test_img)
"""

I'm attaching the badger image; I will try to find time in the next few hours to test on one of your sample images as well.

![American_Badger_CA](https://github.com/JoshOBrien/exiftoolr/assets/54477812/1a616535-933c-47be-95bc-4991f1d1cec2)

**Comment by JoshOBrien** [comment]
@burnsal Thanks. No need to test my sample images, as I've used the files you provided to figure out what's going on. Should have a fix up on GitHub soon, which I'll ask you to test before I polish and submit a new version to CRAN.

**Comment by JoshOBrien** [comment]
@burnsal I've pushed a fix, which involved adding a new `config_file` argument that you can use to supply a path to the config file. Would you mind installing the latest version from GitHub, possibly using this code:

```r
if(!require(devtools)) {install.packages("devtools")}
devtools::install_github("JoshOBrien/exiftoolr")
```

With the new version, something like this (possibly differing only in the path locations) should hopefully work for you as it does for me:

```r
library(exiftoolr)

exif_args <- "-XMP-ctd:CTD_SpV2_PredictedClass=\"American_Badger\""
config_file <- "./cameratrapdetector_metadata.cfg"
test_img <- "American_Badger_CA.jpg"
exif_call(args = exif_args, config_file = config_file, path = test_img)
```

Also, thanks for attaching that photo of a badger. Always fun and rewarding to see how this package is getting used out in the wild!

**Comment by JoshOBrien** [comment]
@burnsal 

Hi again. I think I'd do this by constructing a vector of options, file paths, and punctuating `-execute` options which I would then pass in to `exif_call()`'s `args` argument. (Since, in this approach, the file paths are supplied as part of `args`, you can set the `path=""`.

Probably easiest to see what I mean having a look at this reproducible example:

```r
library(exiftoolr)

config_file <- "./cameratrapdetector_metadata.cfg"

## Prepare an example directory with three jpegs
dir.create("img")
file.copy("American_Badger_CA.jpg", "img/A.jpg", overwrite = TRUE)
file.copy("American_Badger_CA.jpg", "img/B.jpg", overwrite = TRUE)
file.copy("American_Badger_CA.jpg", "img/C.jpg", overwrite = TRUE)
files_vec <- c("img/A.jpg", "img/B.jpg", "img/C.jpg")

## Options may be supplied either as a vector with one element per file...
pred_class <- " -XMP-ctd:CTD_SpV2_PredictedClass="
args_vec <-
    c(paste0(pred_class, "American_Black_Bear"),
      paste0(pred_class, "American_Crow"),
      paste0(pred_class, "Bighorn_Sheep"))

## ... or as a list of vectors with one vector per file
pred_class <- " -XMP-ctd:CTD_SpV2_PredictedClass="
args_vec <-
    list(c(paste0(pred_class, "American_Black_Bear"), "-q"),
         c(paste0(pred_class, "American_Crow"), "-q"),
         c(paste0(pred_class, "Bighorn_Sheep"), "-q"))

## Construct a vector of options and file paths in order you'd supply
## them on the Exiftool command line.
##
## - https://exiftool.org/forum/index.php?topic=10500.0 for
##   explanation of need for "-execute" options
##
## - https://stackoverflow.com/a/25961969/980833 for `c(rbind())`
##   idiom
args <- unlist(c(rbind(args_vec, files_vec, "-execute")))

## Execute a single call to Exiftool. All file paths are passed in as
## part of the `args` argument, so `path` can be left blank.
exif_call(args = args, config_file = config_file, path ="")

## Verify that the above worked
exif_read(dir("img", pattern = "jpg$", full.names = TRUE), 
          tags = "CTD_SpV2_PredictedClass")
## SourceFile CTD_SpV2_PredictedClass
## 1  img/A.jpg     American_Black_Bear
## 2  img/B.jpg           American_Crow
## 3  img/C.jpg           Bighorn_Sheep
```

I've got no sense of whether this is appreciably faster than repeatedly calling `exif_call()`, though I'd be interested to know!

Cheers.

**Comment by JoshOBrien** [comment]
Closing with f6251cad6928912a97dfe7018722c91a53720326, which is incorporated in a new version 0.2.3 that is accepted an on it's way to CRAN.
