### ISSUE TITLE
No functioning version of Exiftool has been found. 

### ISSUE THREAD

**Issue by LafontRapnouilTristan** [JoshOBrien/exiftoolr#5]
Hi Josh,

First, I would like to thank you for this very handy package!

Second, i'd like to report an issue I have to make it work on a new computer :)

I'm working on windows 10 and here are my version info : 
![image](https://user-images.githubusercontent.com/49724216/141098756-a7af651c-0e77-4360-b4d0-1a2f66e94a4e.png)

When installing `exiftoolr` either from `CRAN`or `github` via `install.packages("exiftoolr")` or `devtools::install_github("JoshOBrien/exiftoolr")` seems to work perfectly well as it creates package folder in my `R library. 

Running : 
```
system.file("exiftool", package = "exiftoolr")
```  

returns : 

```
"C:/Users/UsersName/Documents/R/win-library/4.1/exiftoolr/exiftool"
```
As it should.

I then run `install_exiftool()` which do create the `win_exe` folder with `exiftool(-k)` in it.

```
install_exiftool()
```
returns -> 
```
Attempting to download ExifTool from https://exiftool.org/exiftool-12.34.zip
 [100%] Downloaded 6708072 bytes...
Installing ExifTool in C:/Users/UsersName/Documents/R/win-library/4.1/exiftoolr/exiftool/win_exe
```

```
system.file("exiftool/win_exe", package = "exiftoolr")
```
 returns -> 
```
"C:/Users/UsersName/Documents/R/win-library/4.1/exiftoolr/exiftool/win_exe"
```
and 
```
system.file("exiftool/win_exe/exiftool(-k).exe", package = "exiftoolr")
```
 returns -> 
```
"C:/Users/UsersName/Documents/R/win-library/4.1/exiftoolr/exiftool/win_exe/exiftool(-k).exe"
```

So far all seems good to me. 
But when I run `configure_exiftoolr() ` it returns : 
```
Trying perl command: "" --version
Trying perl command: "perl" --version
Trying perl command: "C:\Perl64\bin\perl" --version
Trying perl command: "C:\Perl\bin\perl" --version
Trying perl command: "C:\Strawberry\perl\bin\perl" --version
Trying exiftool command:  -ver
Trying exiftool command: C:/Users/UsersName/Documents/R/win-library/4.1/exiftoolr/exiftool/win_exe/exiftool(-k).exe -ver
Trying exiftool command: exiftool -ver
Error in configure_exiftoolr() : 
  No functioning version of Exiftool has been found. To
download and install a local version into the exiftoolr
package, try doing install_exiftool()
```

I have probably done something wrong but can't figure out what...
Would you have any idea/tips/ or suggestion?

Have a great day and thank you!

**Comment by JoshOBrien** [comment]
Odd that that's not working for you. I wonder what the problem is.

Would you try this command from your R session, and tell me what you get in response?

```r
system2("C:/Users/UsersName/Documents/R/win-library/4.1/exiftoolr/exiftool/win_exe/exiftool(-k).exe", -ver)
```

Also, from a Windows CMD shell, what happens when you type:

```bash
"C:/Users/UsersName/Documents/R/win-library/4.1/exiftoolr/exiftool/win_exe/exiftool(-k).exe" -ver
```

**Comment by LafontRapnouilTristan** [comment]
Hi!

Ok, so when I try your command in R it returns :
![image](https://user-images.githubusercontent.com/49724216/141982608-f286cea8-891a-4c49-80e4-3c8790ccb825.png)

Through the command prompt i got : `12.34`  which seems to be the good version.

Regarding installing an old version I can't as it seems that any older version isn't available in my current R version.
I do not know how "tightly" package version are linked to R and if there is an "easy" way to bypass it.

Thanks again for your answers.

**Comment by LafontRapnouilTristan** [comment]
Hi again!!

I just figured that the "right" command in `R` requires `-ver` between quotes.
It returns `12.34`too!

**Comment by JoshOBrien** [comment]
@LafontRapnouilTristan Does the `"UsersName"` portion of `"C:/Users/UsersName/Documents/R/win-library/4.1/exiftoolr/exiftool/win_exe/exiftool(-k).exe"` (or some other part of that) have a space in it? If so, I think that might be the issue, and am working on a fix for it.

**Comment by LafontRapnouilTristan** [comment]
It does! 

Which is a really bad idea, apologies!
Hope you'll manage to fix this.

Thanks again for the "hotline"!

Have a nice day!

**Comment by JoshOBrien** [comment]
@LafontRapnouilTristan Glad to hear that that's the likely issue. I've made some changes that should make the package now support even people who have spaces in their paths. Would you mind testing the latest version of the package after installing it like this:

```r
if(!require(devtools)) {install.packages("devtools")}
devtools::install_github("JoshOBrien/exiftoolr")
```

and then letting me know how it goes?

Thanks!

**Comment by LafontRapnouilTristan** [comment]
@JoshOBrien Job's done!!

It works perfectly fine!
Thanks again and well done!

**Comment by JoshOBrien** [comment]
@LafontRapnouilTristan Good to hear. Thanks again.
