### ISSUE TITLE
Argument of length zero in configure_exiftoolr()

### ISSUE THREAD

**Issue by tomyamashita** [JoshOBrien/exiftoolr#8]
Hello Josh, 

I've been using your package for a while now and when I updated my version of R to 4.2, I started getting the following error whenever I run exif_call() and exif_read(): 

```
exif_read()
Error in if (com == paste(shQuote(perl_path), shQuote(NULL))) { : 
  argument is of length zero
```

I've tried running both with the path specified and it doesn't work either

```
exif_call(path = "C:/Users/rcyam/AppData/Local/R/win-library/4.2/exiftoolr/exiftool/win_exe")
Trying perl command: "" --version
Trying perl command: "perl" --version
Trying perl command: "C:\Perl64\bin\perl" --version
Trying perl command: "C:\Perl\bin\perl" --version
Trying perl command: "C:\Strawberry\perl\bin\perl" --version
Error in if (com == paste(shQuote(perl_path), shQuote(NULL))) { : 
  argument is of length zero
```

Thanks

**Comment by JoshOBrien** [comment]
What do you get if you run the following commands? Do they work, or do they error out as well?

```r
exif_version()
exif_read(system.file(package = "exiftoolr", "images", "LaSals.jpg"))$LightValue
```

**Comment by tomyamashita** [comment]
I'm getting the same error with both commands

```
> exiftoolr::exif_version()
Error in if (com == paste(shQuote(perl_path), shQuote(NULL))) { : 
  argument is of length zero
> exiftoolr::exif_read(system.file(package = "exiftoolr", "images", "LaSals.jpg"))$LightValue
Error in if (com == paste(shQuote(perl_path), shQuote(NULL))) { : 
  argument is of length zero
```

**Comment by JoshOBrien** [comment]
Hi Tom,

I believe I've fixed the issue with my latest commit. Would you please test it out by downloading the latest version from GitHub by doing, e.g.:

```r
devtools::install_github("JoshOBrien/exiftoolr")
library(exiftoolr)
install_exiftool()
exif_version()
```

Please let me know if that does fix the issue for you.

Thanks,

- Josh

**Comment by tomyamashita** [comment]
Hi Josh, 

This worked. I'm no longer getting the error. Thank you so much. 

Tom

**Comment by schafnoir** [comment]
Hi Josh and Tom,

I was just about to report the same issue! I work with a group of folks who use Windows laptop to run a local Shiny app I developed to examine batches of photos that we collect as part of environmental monitoring. Upon updating from R 4.1.X to R 4.2.X, it appeared that `exiftoolr::configure_exiftoolr()` could no longer find perl, but oddly, the lack of perl on the Windows machines never was an issue with R 4.1.X.

I'll touch base with some of my staff to see if the latest Git commit of exiftoolr resolves our problems as well. Josh, I sure appreciate how responsive you are, and our group has definitely benefited from what exiftoolr can do!

Cheers,
Courtney Meier

**Comment by JoshOBrien** [comment]
@schafnoir Glad you've found good use for the package! I just submitted a new version, containing the fix to the problem you and Tom experienced, to CRAN, so it should be up there soon. Will check back in here to close this issue and let you know once I get the confirmation it's been accepted.

Cheers,

- Josh

**Comment by JoshOBrien** [comment]
@schafnoir Version 0.1.8, with the fix, has been accepted by CRAN. The sources are already up there, and the Windows binaries should follow within a day or two.

**Comment by schafnoir** [comment]
@JoshOBrien - great news, thank you so much for the update!
